### ISSUE TITLE
Can't click "minimize, close, make bigger"

### ISSUE THREAD

**Issue by siiparch** [KiKaraage/ArcWTF#11]
When sidebery is active, i can't click those buttons 

![Screenshot 2024-02-20 204145](https://github.com/KiKaraage/ArcWTF/assets/103263637/d8e3c72b-17ba-445d-9d8a-045ef5612df9)

But if i click on sidebery and return to horizontal tabs, those buttons are clickable

is there a way to solve that?

**Comment by KiKaraage** [comment]
Can you provide your current conditions? (Browser: Firefox, Floorp or Librewolf? Which version? OS: Windows 10 or 11?) I assume this is already the newest version of my theme because of the automatic tab bar hiding mechanism. 

Personally I and most user esp on Windows doesn't experience this, so you might want to try changing some values on the [hide-tabs-bar CSS](https://github.com/KiKaraage/ArcWTF/blob/main/tweaks/hide-tabs-bar.css), line 71-88.

**Comment by KiKaraage** [comment]
Okay! While I personally don't experienced it, I just found out that the bug does existed in edge-frfox too and the OP, bmFtZQ, has released a fix for it. I will push an update this weekend (with improvement to the Sidebery layout as well!)

**Comment by siiparch** [comment]
Perhaps I should've added more information about my setup:
I'm using Firefox Version: 
![image](https://github.com/KiKaraage/ArcWTF/assets/103263637/55a4e4fa-7235-4c1e-a182-cd06bff7e3e7)

This is my Windows Version:
![image](https://github.com/KiKaraage/ArcWTF/assets/103263637/c78c93b7-2827-404f-8d53-59a80c2b0de1)

I've installed firefox trough winget yesterday, the only change i've made to vanilla firefox besides Arc-WTF, is the custom user.js called "fastfox".

Those are my extensions: 
![image](https://github.com/KiKaraage/ArcWTF/assets/103263637/ca494901-7dc5-4d18-83e0-9bdea321b78d)

**Comment by KiKaraage** [comment]
Yeah it's because of the Firefox v123 update!

I will push a new update in a few days, but in the meantime you can update the [hide-tabs-bar.css](KiKaraage/ArcWTF/main/tweaks/hide-tabs-bar.css)
